langauge: cpp

compiler:
  - gcc
  - clang

before_install:
  - "cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libgtest* /usr/local/lib/ && cd -"

script:
  - cmake . && make && make test

addons:
  apt:
    packages:
      - cmake
      - libgtest-dev
      - build-essential
